### ISSUE TITLE
`useSub` hook doesn't update mapper function when dependencies change

### ISSUE THREAD

**Issue by abdulhadi-lababidi98** [fdc-viktor-luft/react-use-sub#8]
### Situation
When utilizing the `useSub` hook with a mapper function dependent on a changing props, unexpected behavior occurs. 

### Code Example
```
const ComponentName: React.FC<{ featureSetID: string }> = ({ featureSetID }) => {
    const featureSet = useSub(
        ({ featureSet }): FeatureSet | undefined => featureSet.featureSets[featureSetID]
    );
        
    useEffect(()=>{
        console.log("featureSetID Changed")
    },[featureSetID])
    
    useEffect(()=>{
        console.log("featureSet Changed")
    },[featureSet])
    
    return <></>
};
```

### Expected Behavior
The expected behavior is that whenever the featureSetID changes, the returned featureSet also changes accordingly.

### Actual Behavior
However, what actually happens is when the featureSetID changes, the featureSet remains the same.

### Issue Cause
Upon investigation, the root cause of the issue seems to be that the mapper function doesn't get updated when the featureSetID changes, causing it to retain the old ID.

### Workaround
The issue was resolved by removing any dependencies of the mapper function, which is not intuitive and led to hours of debugging. 
```
    const featureSets = useSharedAuthSub(
        ({ featureSet }): Record<string, FeatureSet | undefined> => featureSet.featureSets
    );

    const featureSet = featureSets[featureSetID];
```

### Suggested solution 
Allow passing a dependency array to the useSub hook so the mapper function will get updated whenever these dependencies get updated, similar to how we do in useCallback, useEffect, etc.
```
const featureSet = useSub(
    ({ featureSet }): FeatureSet | undefined => featureSet.featureSets[featureSetID],
    [featureSetID]
);
```
To maintain backward compatibility, making this array of dependencies optional would be beneficial.
This change would enhance the usability and intuitiveness of the useSub hook, preventing similar debugging endeavors in the future.

**Comment by fdc-viktor-luft** [comment]
Your suggestion is exactly what was necessary in v2 of react-use-sub. And this isn't necessary anymore. I also could not reproduce your issue. See here:

https://stackblitz.com/edit/react-ts-yfcxgq?file=package.json,store.ts,Component.tsx,App.tsx

Please create first a minimal reproduction of your issue.

**Comment by abdulhadi-lababidi98** [comment]
After investigating this further, I found out that in our project we use version `2.2.2` of react-use-sub, instead of the latest version. As mentioned in the renovate configs
> react-use-sub 3.0.0 is incompatible with storybook 7.
> we get an error due to the react-use-sub dependency. Error: Build failed with 1 error:
> `ERR! ../node_modules/.pnpm/react-use-sub@3.0.1_react-dom@18.2.0_react@18.2.0/node_modules/react-use-sub/dist/esm/index.js:1:17: ERROR: No matching export in "global-externals:react" for import "useSyncExternalStore"`

But probably upgrading to Storybook V8 will solve this? anyway I'll close this issue because it's not relevant anymore.

**Comment by fdc-viktor-luft** [comment]
In most recent version of Storybook they allow the peer to provide the used React version, so this issue should not exist there anymore.
